# This notebook covers some of the most fundamental concepts of tensors using TensorFlow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (TPUs)
* Exercises

## Introduction to Tensors
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matirx: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
# Check the dimension of the vector
vector.ndim

1

In [9]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
# Check the dimendsions of the matrix
matrix.ndim

2

In [14]:
# Create another matrix
matrix_float = tf.constant([[10., 7.],
                            [3., 2.],
                            [8., 9.]], dtype=tf.float16)
matrix_float

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
# Dimensions of the float_matrix
matrix_float.ndim

2

In [15]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [16]:
# Dimensions of the tensor
tensor.ndim

3